web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/wechatApiTest/public
  ports:
    - "80:8000"
  links:
    - db
  volumes:
    - .:/code
db:
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: wechat
    MYSQL_ROOT_PASSWORD: 12345
